# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{tu-context}
  s.version = "0.5.8"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jeremy McAnally", "Rails Core", "Pratik Naik"]
  s.date = %q{2010-07-02}
  s.description = %q{If you've ever wanted contexts in your Test::Unit tests, then context is for you.  Your tests will be easier to read and write without all the magic and extra code smell!}
  s.email = %q{jeremymcanally@gmail.com}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "License.txt",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/tu-context.rb",
     "lib/tu-context/context.rb",
     "lib/tu-context/core_ext/rails_hacks.rb",
     "lib/tu-context/core_ext/string.rb",
     "lib/tu-context/lifecycle.rb",
     "lib/tu-context/shared_behavior.rb",
     "lib/tu-context/suite.rb",
     "lib/tu-context/test.rb",
     "lib/tu-context/version.rb",
     "tasks/deployment.rake",
     "tasks/environment.rake",
     "test/test_context.rb",
     "test/test_core_ext.rb",
     "test/test_helper.rb",
     "test/test_lifecycle.rb",
     "test/test_nested_lifecycle.rb",
     "test/test_shared.rb",
     "test/test_shared_lifecycle.rb",
     "test/test_test.rb",
     "tu-context.gemspec"
  ]
  s.homepage = %q{http://github.com/djsun/context}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Adds context blocks for Test::Unit}
  s.test_files = [
    "test/test_context.rb",
     "test/test_core_ext.rb",
     "test/test_helper.rb",
     "test/test_lifecycle.rb",
     "test/test_nested_lifecycle.rb",
     "test/test_shared.rb",
     "test/test_shared_lifecycle.rb",
     "test/test_test.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

